const sampleLots=[{lotId:'L1',releaseTime:0,transportTime:8,dueTime:10},{lotId:'L2',releaseTime:0,transportTime:7,dueTime:9},{lotId:'L3',releaseTime:1,transportTime:6,dueTime:8},{lotId:'L4',releaseTime:2,transportTime:5,dueTime:10},{lotId:'L5',releaseTime:3,transportTime:9,dueTime:13},{lotId:'L6',releaseTime:4,transportTime:4,dueTime:12}];
const colors=['#2f7d7e','#c35d37','#7d6b2f','#5c6bc0','#00897b','#8d5a97'];
let lots=structuredClone(sampleLots);let currentProject=null;
const $=s=>document.querySelector(s),lotRows=$('#lotRows'),scheduleRows=$('#scheduleRows'),kpiCards=$('#kpiCards'),kpiBars=$('#kpiBars'),gantt=$('#gantt'),resultArea=$('#resultArea'),errorBox=$('#errorBox');
$('#sampleButton').onclick=()=>{lots=structuredClone(sampleLots);currentProject=null;resultArea.classList.add('hidden');renderLots();};
$('#addLotButton').onclick=()=>{lots.push({lotId:`L${lots.length+1}`,releaseTime:0,transportTime:1,dueTime:1});renderLots();};
$('#runButton').onclick=()=>{try{const ohtCount=Number($('#ohtCount').value),algorithm=$('#algorithm').value,schedule=scheduleLots(lots,ohtCount,algorithm);currentProject={algorithm,ohtCount,createdAt:new Date(),lots:structuredClone(lots),schedule,kpi:calculateKpi(schedule,ohtCount)};hideError();renderResult(currentProject);}catch(e){showError(e.message);}};
$('#exportButton').onclick=()=>{if(currentProject)downloadExcel(currentProject);};
function renderLots(){lotRows.innerHTML='';lots.forEach((lot,index)=>{const row=document.createElement('tr');row.innerHTML=`<td><input value="${esc(lot.lotId)}" data-index="${index}" data-key="lotId"></td><td class="number"><input type="number" min="0" step="1" value="${lot.releaseTime}" data-index="${index}" data-key="releaseTime"></td><td class="number"><input type="number" min="0" step="1" value="${lot.transportTime}" data-index="${index}" data-key="transportTime"></td><td class="number"><input type="number" min="0" step="1" value="${lot.dueTime}" data-index="${index}" data-key="dueTime"></td><td class="action-cell"><button type="button" data-remove="${index}" ${lots.length===1?'disabled':''}>Delete</button></td>`;lotRows.appendChild(row);});lotRows.querySelectorAll('input').forEach(input=>input.oninput=e=>{const t=e.currentTarget,i=Number(t.dataset.index),k=t.dataset.key;lots[i][k]=k==='lotId'?t.value:Number(t.value);});lotRows.querySelectorAll('button[data-remove]').forEach(button=>button.onclick=e=>{lots=lots.filter((_,i)=>i!==Number(e.currentTarget.dataset.remove));renderLots();});}
function scheduleLots(inputLots,ohtCount,algorithm){validate(inputLots,ohtCount);const unfinished=structuredClone(inputLots),ohts=Array.from({length:ohtCount},(_,i)=>({ohtId:`OHT${i+1}`,availableTime:0})),result=[];while(unfinished.length){const oht=ohts.slice().sort((a,b)=>a.availableTime-b.availableTime||ohtNo(a.ohtId)-ohtNo(b.ohtId))[0];const available=unfinished.filter(l=>l.releaseTime<=oht.availableTime);if(!available.length){oht.availableTime=Math.min(...unfinished.filter(l=>l.releaseTime>oht.availableTime).map(l=>l.releaseTime));continue;}const lot=available.slice().sort((a,b)=>compareLots(a,b,algorithm))[0],startTime=Math.max(oht.availableTime,lot.releaseTime),finishTime=startTime+lot.transportTime,tardiness=Math.max(0,finishTime-lot.dueTime),earliness=Math.max(0,lot.dueTime-finishTime);result.push({lotId:lot.lotId,ohtId:oht.ohtId,releaseTime:lot.releaseTime,transportTime:lot.transportTime,startTime,finishTime,dueTime:lot.dueTime,tardiness,earliness});oht.availableTime=finishTime;unfinished.splice(unfinished.findIndex(x=>x.lotId===lot.lotId),1);}return result;}
function validate(inputLots,ohtCount){if(!Number.isFinite(ohtCount)||ohtCount<=0)throw new Error('OHT Count must be greater than 0');const seen=new Set();inputLots.forEach(l=>{if(!String(l.lotId).trim())throw new Error('Lot ID is required');if(seen.has(l.lotId))throw new Error(`Duplicate Lot ID: ${l.lotId}`);if(l.releaseTime<0)throw new Error(`${l.lotId} Release Time must be >= 0`);if(l.transportTime<=0)throw new Error(`${l.lotId} Transport Time must be > 0`);if(l.dueTime<0)throw new Error(`${l.lotId} Due Time must be >= 0`);seen.add(l.lotId);});}
function compareLots(a,b,algorithm){if(algorithm==='EDD')return a.dueTime-b.dueTime||a.releaseTime-b.releaseTime||a.lotId.localeCompare(b.lotId);if(algorithm==='SPT')return a.transportTime-b.transportTime||a.releaseTime-b.releaseTime||a.lotId.localeCompare(b.lotId);return a.releaseTime-b.releaseTime||a.lotId.localeCompare(b.lotId);}function ohtNo(id){return Number(id.replace('OHT',''));}
function calculateKpi(entries,ohtCount){if(!entries.length)return{makespan:0,averageFlowTime:0,totalTardiness:0,averageTardiness:0,onTimeDeliveryRate:0,ohtUtilization:0};const makespan=Math.max(...entries.map(e=>e.finishTime)),totalTardiness=sum(entries.map(e=>e.tardiness)),totalTransport=sum(entries.map(e=>e.transportTime)),onTime=entries.filter(e=>e.tardiness===0).length;return{makespan,averageFlowTime:round(sum(entries.map(e=>e.finishTime-e.releaseTime))/entries.length),totalTardiness,averageTardiness:round(totalTardiness/entries.length),onTimeDeliveryRate:round(onTime/entries.length),ohtUtilization:round(totalTransport/(makespan*ohtCount))};}
function renderResult(project){const rows=kpiRows(project.kpi);resultArea.classList.remove('hidden');kpiCards.innerHTML=rows.map(r=>`<div class="kpi-card"><span>${r.label}</span><strong>${r.value}</strong></div>`).join('');scheduleRows.innerHTML=project.schedule.map(e=>`<tr><td>${e.lotId}</td><td>${e.ohtId}</td><td class="number">${e.startTime}</td><td class="number">${e.finishTime}</td><td class="number">${e.dueTime}</td><td class="number">${e.tardiness}</td><td class="number">${e.earliness}</td></tr>`).join('');renderGantt(project.schedule);renderKpiBars(rows);}
function renderGantt(entries){const makespan=Math.max(...entries.map(e=>e.finishTime),1),ohtIds=[...new Set(entries.map(e=>e.ohtId))];gantt.innerHTML=ohtIds.map((id,row)=>`<div class="gantt-row"><div class="gantt-label">${id}</div><div class="gantt-track">${entries.filter(e=>e.ohtId===id).map((e,i)=>`<div class="gantt-bar" title="${e.lotId}: ${e.startTime} - ${e.finishTime}" style="left:${e.startTime/makespan*100}%;width:${Math.max((e.finishTime-e.startTime)/makespan*100,6)}%;background:${colors[(row+i)%colors.length]}">${e.lotId}</div>`).join('')}</div></div>`).join('')+`<div class="time-axis"><span>0</span><span>${makespan}</span></div>`;}
function renderKpiBars(rows){const max=Math.max(...rows.map(r=>r.rawValue),1);kpiBars.innerHTML=rows.map(r=>`<div class="bar-row"><strong>${r.label}</strong><div class="bar-track"><div class="bar-fill" style="width:${r.rawValue/max*100}%"></div></div><span>${r.value}</span></div>`).join('');}
function kpiRows(k){return[{label:'Makespan',value:fmt(k.makespan),rawValue:k.makespan},{label:'Avg Flow',value:fmt(k.averageFlowTime),rawValue:k.averageFlowTime},{label:'Total Tardiness',value:fmt(k.totalTardiness),rawValue:k.totalTardiness},{label:'Avg Tardiness',value:fmt(k.averageTardiness),rawValue:k.averageTardiness},{label:'On-Time Rate',value:pct(k.onTimeDeliveryRate),rawValue:k.onTimeDeliveryRate},{label:'Utilization',value:pct(k.ohtUtilization),rawValue:k.ohtUtilization}];}
function downloadExcel(p){if(typeof XLSX==='undefined'){showError('Excel library is still loading. Please try again.');return;}const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Scheduling Rule',p.algorithm],['OHT Count',p.ohtCount],['Create Time',p.createdAt.toLocaleString()],[],['Lot','Release Time','Transport Time','Due Time'],...p.lots.map(l=>[l.lotId,l.releaseTime,l.transportTime,l.dueTime])]),'Input_Data');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Lot','OHT','Start','Finish','Due','Tardiness','Earliness'],...p.schedule.map(e=>[e.lotId,e.ohtId,e.startTime,e.finishTime,e.dueTime,e.tardiness,e.earliness])]),'Schedule_Result');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['KPI','Value'],['Makespan',p.kpi.makespan],['Average Flow Time',p.kpi.averageFlowTime],['Total Tardiness',p.kpi.totalTardiness],['Average Tardiness',p.kpi.averageTardiness],['On-Time Rate',p.kpi.onTimeDeliveryRate],['OHT Utilization',p.kpi.ohtUtilization]]),'KPI');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['OHT','Lot','Start','Finish'],...p.schedule.map(e=>[e.ohtId,e.lotId,e.startTime,e.finishTime])]),'Gantt_Data');XLSX.writeFile(wb,`Scheduling_Report_${stamp(p.createdAt)}.xlsx`);}
function sum(v){return v.reduce((a,b)=>a+b,0)}function round(v){return Math.round(v*10000)/10000}function fmt(v){return Number(v.toFixed(4)).toString()}function pct(v){return `${(v*100).toFixed(1)}%`}function stamp(d){const p=v=>String(v).padStart(2,'0');return `${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}_${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`}function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}function showError(m){errorBox.textContent=m;errorBox.classList.remove('hidden')}function hideError(){errorBox.classList.add('hidden');errorBox.textContent=''}
renderLots();
